name: 🚀 Build and deploy
run-name: ${{ github.actor }} is deploying with GitHub Actions 🚀
on:
  push:

jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - run: echo "Lancement des tests"
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "Le code du dépôt a été cloné sur le serveur d'exécution."
      - run: npm clean-install
      - run: npm run test:cov

  build:
    runs-on: ubuntu-latest
    needs:
    - test
    steps:
      - run: echo "Lancement des étapes de construction"
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "Le code du dépôt a été cloné sur le serveur d'exécution."
      - run: npm clean-install
      - run: npm run build
      - name: Save cache (node_modules)
        uses: actions/cache/save@v4
        with:
          path: |
            node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
      - run : echo "🏁 Étapes de construction terminées"

  build-push-docker :
    runs-on: ubuntu-latest
    if: contains(github.ref, 'recette')
    permissions:
      contents: read
      packages: write
    env: 
      DATABASE_URL: "mysql://leadAdmin:leadAdminP@55w0rd@database:3306/vivactive?schema=public"
      NEST_PUBLIC_CLERK_PUBLISHABLE_KEY: pk_test_aGVhbHRoeS1waWdlb24tNjUuY2xlcmsuYWNjb3VudHMuZGV2JA
      CLERK_SECRET_KEY: sk_test_EVJU56xeaHsnNrW32eMimpo1TOOjTkzPzc6TvC1ODX
      ENV_DATABASE: vivactive
      ENV_USER: leadAdmin
      ENV_PASSWORD: leadAdminP@55w0rd
    needs:
    - test
    steps:
    - uses: actions/checkout@v4 #recupérer le code
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: Build and push docker
      uses: docker/build-push-action@v6
      with: 
        context : .
        push: true
        target: vivactive-api #nom de l'image concerné dans le Dockerfile
        tags: ghcr.io/cda-24-a/vivactive_api/vivactive-api-backend:recette  